spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-rest-api?serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #Com Flyway ï¿½ none
    open-in-view: false

  #flyway:
   # enabled: true


logging:
  level:
    org.flywaydb: debug
